CREATE TABLE [dbo].[CCB_CORTA_POSICION](
	[NO_ORDEN] [nvarchar](40) NOT NULL,
	[CCB] [nvarchar](35) NOT NULL,
	[CANTIDAD] [nvarchar](17) NULL,
	[ITEM] [nvarchar](5) NULL,
	[DESCRIPCION_ITEM] [nvarchar](150) NULL,
	[PRECIO] [nvarchar](17) NULL,
	[PROCESADO] [nvarchar](2) NULL,
	[FECHA_INSERCION] [nvarchar](10) NULL,
	[HORA_INSERCION] [nvarchar](10) NULL,
 CONSTRAINT [PK_CCB_CORTA_POSICION] PRIMARY KEY CLUSTERED 
(
	[NO_ORDEN] ASC,
	[CCB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]