CREATE TABLE [dbo].[CCB_Suministro](
	[RFC] [nvarchar](15) NOT NULL,
	[CCB] [nvarchar](35) NOT NULL,
	[CLIENTE] [nvarchar](100) NULL,
 CONSTRAINT [PK_CCB_Suministro] PRIMARY KEY CLUSTERED 
(
	[RFC] ASC,
	[CCB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]