CREATE TABLE [dbo].[CCB_CORTA_IMSS](
	[NO_ORDEN] [nvarchar](40) NOT NULL,
	[NO_CONTRATO] [nvarchar](40) NULL,
	[NO_SOLICITUD] [nvarchar](40) NULL,
	[LUGAR_ENTREGA] [nvarchar](15) NULL,
	[ALMACEN_DESTINO] [nvarchar](15) NULL,
	[ALMACEN_ENTREGA] [varchar](150) NULL,
	[DIRECCION_ALMACEN] [varchar](150) NULL,
	[CLUES] [nvarchar](150) NULL,
	[ENTIDAD_FEDERATIVA] [nvarchar](20) NULL,
	[PROCEDIMIENTO] [nvarchar](25) NULL,
	[FIANZA] [nvarchar](25) NULL,
	[PARTIDA_PRESUPUESTAL] [nvarchar](7) NULL,
	[NO_PROYECTO] [nvarchar](50) NULL,
	[NO_ADQUISICION] [nvarchar](25) NULL,
	[PROVEEDOR] [nvarchar](30) NULL,
	[ALMACEN] [nvarchar](50) NULL,
	[CANTIDAD_TOTAL] [nvarchar](5) NULL,
	[SUBTOTAL] [nvarchar](15) NULL,
	[MONTO_TOTAL] [nvarchar](15) NULL,
	[INSTITUCION] [nvarchar](15) NULL,
	[CLUE] [nvarchar](60) NULL,
	[PROCESADO] [nvarchar](2) NULL,
	[FECHA_INSERCION] [nvarchar](10) NULL,
	[HORA_INSERCION] [nvarchar](10) NULL,
	[FECHA_PROCESADO] [nvarchar](10) NULL,
	[HORA_PROCESADO] [nvarchar](10) NULL,
	[STATUS] [nvarchar](20) NULL,
	[ESTATUS_CLIENTE] [nvarchar](250) NULL,
	[RFC] [nvarchar](16) NULL,
	[FECHA_ENTREGA] [nvarchar](10) NULL,
	[FECHA_EMISION] [nvarchar](10) NULL,
	[CLIENTE] [nvarchar](255) NULL,
	[ID_CS] [int] NULL,
 CONSTRAINT [PK_OR_CORTA_IMSS] PRIMARY KEY CLUSTERED 
(
	[NO_ORDEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCB_CORTA_IMSS]  WITH CHECK ADD  CONSTRAINT [FK_CCB_CORTA_IMSS_INTERLOCUTORES] FOREIGN KEY([LUGAR_ENTREGA])
REFERENCES [dbo].[INTERLOCUTORES] ([LUGAR_ENTREGA])
GO

ALTER TABLE [dbo].[CCB_CORTA_IMSS] CHECK CONSTRAINT [FK_CCB_CORTA_IMSS_INTERLOCUTORES]
GO
ALTER TABLE [dbo].[CCB_CORTA_IMSS]  WITH CHECK ADD  CONSTRAINT [FK_CCB_CORTA_IMSS_INTERLOCUTORES1] FOREIGN KEY([ALMACEN_DESTINO])
REFERENCES [dbo].[INTERLOCUTORES] ([LUGAR_ENTREGA])
GO

ALTER TABLE [dbo].[CCB_CORTA_IMSS] CHECK CONSTRAINT [FK_CCB_CORTA_IMSS_INTERLOCUTORES1]
GO
ALTER TABLE [dbo].[CCB_CORTA_IMSS] ADD  CONSTRAINT [DF_CCB_CORTA_IMSS_PROCESADO]  DEFAULT ('N') FOR [PROCESADO]