CREATE TABLE [dbo].[INTERLOCUTORES_INSABI](
	[CLUE] [nvarchar](60) NOT NULL,
	[DESTINATARIO_MERCANCIA] [nvarchar](15) NULL,
 CONSTRAINT [PK_INTERLOCUTORES_INSABI] PRIMARY KEY CLUSTERED 
(
	[CLUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]