
ALTER ROLE [db_accessadmin] ADD MEMBER [NT AUTHORITY\SYSTEM]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [NT AUTHORITY\SYSTEM]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [NT AUTHORITY\SYSTEM]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [FARMAYPO\novis.sql]
GO
ALTER ROLE [db_owner] ADD MEMBER [FARMAYPO\jorge.chavero]
GO
ALTER ROLE [db_owner] ADD MEMBER [FARMAYPO\cesar.vazquez]